apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  # mysql 的 claim
  name: webook-mysql-claim
spec:
  storageClassName: local-storage
  # 访问模式
  accessModes:
    - ReadWriteOnce
  # 资源请求
  resources:
    requests:
      storage: 1Gi 